### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by MKM12345** [hamdivazim/UnityGame#1]
Hello @hamdivazim and @Octoboss1305,

You guys haven't been doing much here and the code seems dead. If you would tell me what you are making with its logic I'll help you make your game.

Just tell me please.

**Comment by hamdivazim-archive** [comment]
It's a gravity ball game we tried making but eventually didn't get the time to. Thanks for offering, but it's unlikely development on this game will continue at all.

**Comment by MKM12345** [comment]
I can do it all I need is permission and the game logic.

**Comment by hamdivazim-archive** [comment]
You could make a repo and use pygame on your own account if you want, but this repo's dead. I'll be happy to collaborate with you on that, if you are happy with it

**Comment by MKM12345** [comment]
Ok sure.

**Comment by hamdivazim-archive** [comment]
If you want me to collaborate with you could you please send a request to, and I will try my best to help you

**Comment by MKM12345** [comment]
I just made it and I will send you a request.
